### ISSUE TITLE
Move sbt-github-actions to sbt org

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-github-actions#117]
Firstly @djspiewak I wanted to thank you for this awesome project, its really helped reduce the maintenance burden of many OS projects as I am sure you know.

Unfortunately at least on the outside it seems like you don't have much time to maintain the project which is completely understandable. I spoke with @SethTisue earlier and we both agreed that it would be a good idea (with your permission of course) to migrate the project to sbt repo so that it can be more actively maintained by the OS community. @eed3si9n has done similar things in the past.

Thoughts?

**Comment by djspiewak** [comment]
The fact that it took me *this* long to get to this issue is perhaps the best indication of how much I haven't been able to maintain this project recently… My apologies.

I think that moving this to the sbt organization is absolutely the right thing to do. IMO this type of functionality is pretty fundamental infrastructure, and it deserves a set of maintainers who can keep up with it. Ultimately, I think two things should happen near-term:

- Move this project (also ideally https://github.com/djspiewak/sbt-github-packages) to a more sustainable maintainership state. The sbt org is perfect
- Re-consolidate functionality from https://github.com/typelevel/sbt-typelevel back into this plugin, where it can be shared and jointly evolved (poking @armanbilge)

One step at a time though. I'm very much agreed with you, @sethtisue, and @eed3si9n.

**Comment by eed3si9n** [comment]
If you can transfer it to me (eed3si9n), I can then move it to sbt org, and setup a team with write rights to the repo.

**Comment by djspiewak** [comment]
Done

**Comment by eed3si9n** [comment]
Move is done. https://github.com/orgs/sbt/teams/sbt-github-actions/members has Maintainer rights, and I'd be happy to add more. Note if we do later setup automatic publishing, then pushing tags would have consequences, so we should generally keep the team to small circle of trusted people.

**Comment by mdedetrich** [comment]
@eed3si9n I would be happy to help maintain, I integrated sbt-github-actions into many Scala OS projects and also use it in 2 projects I am currently maintaining (Guardian and Pekko).

Would really like to push the project further to add more functionality into it.

**Comment by eed3si9n** [comment]
Invite sent to Matthew and Arman. Closing this ticket for now.
